language: node_js
node_js:
- '0.10'
deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: am-guac
  env: amGuac-dev
  bucket_name: am-guac
  access_key_id: AKIAI32MQWTO3XQVB5WA
  secret-access-key:
    secure: qKieCoZR6fT4i4P6IEIUSRQHCsxBfhVYb0AnpHoMqZchtJy2pA4jo7rUKjM2Fm16w5cMnuQ5zZfc7Dt24OYShNgAlQHTaNb0sQ//AAOF2+eExRjNuZ+fLBwboZXW9gzdUFLZQJkWLFfCHD0yx1BPBPZFq0n9c3iWb9loMrcX6Ws=